development:
  adapter: postgresql
  encoding: unicode
  database: oauth_doorkeeper_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: oauth_doorkeeper_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: oauth_doorkeeper_production
  pool: 5
  username:
  password:

